# Generated by Django 5.0.7 on 2024-08-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='Product',
            new_name='product',
        ),
    ]
