# Generated by Django 5.0.7 on 2024-08-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0002_alter_mailing_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailsender.client'),
        ),
    ]
