# Generated by Django 5.0.7 on 2024-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_mailingattempt_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_mailing_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
