# Generated by Django 5.0.7 on 2024-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0004_mailing_last_mailing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='last_mailing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
